// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -package etcdclient -source client.go -destination=client_mock.go Client
//

// Package etcdclient is a generated GoMock package.
package etcdclient

import (
	context "context"
	io "io"
	reflect "reflect"

	clientv3 "go.etcd.io/etcd/client/v3"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AlarmDisarm mocks base method.
func (m_2 *MockClient) AlarmDisarm(ctx context.Context, m *clientv3.AlarmMember) (*clientv3.AlarmResponse, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "AlarmDisarm", ctx, m)
	ret0, _ := ret[0].(*clientv3.AlarmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AlarmDisarm indicates an expected call of AlarmDisarm.
func (mr *MockClientMockRecorder) AlarmDisarm(ctx, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlarmDisarm", reflect.TypeOf((*MockClient)(nil).AlarmDisarm), ctx, m)
}

// AlarmList mocks base method.
func (m *MockClient) AlarmList(ctx context.Context) (*clientv3.AlarmResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlarmList", ctx)
	ret0, _ := ret[0].(*clientv3.AlarmResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AlarmList indicates an expected call of AlarmList.
func (mr *MockClientMockRecorder) AlarmList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlarmList", reflect.TypeOf((*MockClient)(nil).AlarmList), ctx)
}

// AuthDisable mocks base method.
func (m *MockClient) AuthDisable(ctx context.Context) (*clientv3.AuthDisableResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthDisable", ctx)
	ret0, _ := ret[0].(*clientv3.AuthDisableResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthDisable indicates an expected call of AuthDisable.
func (mr *MockClientMockRecorder) AuthDisable(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthDisable", reflect.TypeOf((*MockClient)(nil).AuthDisable), ctx)
}

// AuthEnable mocks base method.
func (m *MockClient) AuthEnable(ctx context.Context) (*clientv3.AuthEnableResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthEnable", ctx)
	ret0, _ := ret[0].(*clientv3.AuthEnableResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthEnable indicates an expected call of AuthEnable.
func (mr *MockClientMockRecorder) AuthEnable(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthEnable", reflect.TypeOf((*MockClient)(nil).AuthEnable), ctx)
}

// AuthStatus mocks base method.
func (m *MockClient) AuthStatus(ctx context.Context) (*clientv3.AuthStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthStatus", ctx)
	ret0, _ := ret[0].(*clientv3.AuthStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthStatus indicates an expected call of AuthStatus.
func (mr *MockClientMockRecorder) AuthStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthStatus", reflect.TypeOf((*MockClient)(nil).AuthStatus), ctx)
}

// Authenticate mocks base method.
func (m *MockClient) Authenticate(ctx context.Context, name, password string) (*clientv3.AuthenticateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticate", ctx, name, password)
	ret0, _ := ret[0].(*clientv3.AuthenticateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Authenticate indicates an expected call of Authenticate.
func (mr *MockClientMockRecorder) Authenticate(ctx, name, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticate", reflect.TypeOf((*MockClient)(nil).Authenticate), ctx, name, password)
}

// Close mocks base method.
func (m *MockClient) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// Compact mocks base method.
func (m *MockClient) Compact(ctx context.Context, rev int64, opts ...clientv3.CompactOption) (*clientv3.CompactResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, rev}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Compact", varargs...)
	ret0, _ := ret[0].(*clientv3.CompactResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compact indicates an expected call of Compact.
func (mr *MockClientMockRecorder) Compact(ctx, rev any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, rev}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compact", reflect.TypeOf((*MockClient)(nil).Compact), varargs...)
}

// Defragment mocks base method.
func (m *MockClient) Defragment(ctx context.Context, endpoint string) (*clientv3.DefragmentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Defragment", ctx, endpoint)
	ret0, _ := ret[0].(*clientv3.DefragmentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Defragment indicates an expected call of Defragment.
func (mr *MockClientMockRecorder) Defragment(ctx, endpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Defragment", reflect.TypeOf((*MockClient)(nil).Defragment), ctx, endpoint)
}

// Delete mocks base method.
func (m *MockClient) Delete(ctx context.Context, key string, opts ...clientv3.OpOption) (*clientv3.DeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*clientv3.DeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockClientMockRecorder) Delete(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClient)(nil).Delete), varargs...)
}

// Do mocks base method.
func (m *MockClient) Do(ctx context.Context, op clientv3.Op) (clientv3.OpResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", ctx, op)
	ret0, _ := ret[0].(clientv3.OpResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockClientMockRecorder) Do(ctx, op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockClient)(nil).Do), ctx, op)
}

// Get mocks base method.
func (m *MockClient) Get(ctx context.Context, key string, opts ...clientv3.OpOption) (*clientv3.GetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*clientv3.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClientMockRecorder) Get(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClient)(nil).Get), varargs...)
}

// Grant mocks base method.
func (m *MockClient) Grant(ctx context.Context, ttl int64) (*clientv3.LeaseGrantResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Grant", ctx, ttl)
	ret0, _ := ret[0].(*clientv3.LeaseGrantResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Grant indicates an expected call of Grant.
func (mr *MockClientMockRecorder) Grant(ctx, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Grant", reflect.TypeOf((*MockClient)(nil).Grant), ctx, ttl)
}

// HashKV mocks base method.
func (m *MockClient) HashKV(ctx context.Context, endpoint string, rev int64) (*clientv3.HashKVResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashKV", ctx, endpoint, rev)
	ret0, _ := ret[0].(*clientv3.HashKVResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashKV indicates an expected call of HashKV.
func (mr *MockClientMockRecorder) HashKV(ctx, endpoint, rev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashKV", reflect.TypeOf((*MockClient)(nil).HashKV), ctx, endpoint, rev)
}

// KeepAlive mocks base method.
func (m *MockClient) KeepAlive(ctx context.Context, id clientv3.LeaseID) (<-chan *clientv3.LeaseKeepAliveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeepAlive", ctx, id)
	ret0, _ := ret[0].(<-chan *clientv3.LeaseKeepAliveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeepAlive indicates an expected call of KeepAlive.
func (mr *MockClientMockRecorder) KeepAlive(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeepAlive", reflect.TypeOf((*MockClient)(nil).KeepAlive), ctx, id)
}

// KeepAliveOnce mocks base method.
func (m *MockClient) KeepAliveOnce(ctx context.Context, id clientv3.LeaseID) (*clientv3.LeaseKeepAliveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeepAliveOnce", ctx, id)
	ret0, _ := ret[0].(*clientv3.LeaseKeepAliveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeepAliveOnce indicates an expected call of KeepAliveOnce.
func (mr *MockClientMockRecorder) KeepAliveOnce(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeepAliveOnce", reflect.TypeOf((*MockClient)(nil).KeepAliveOnce), ctx, id)
}

// Leases mocks base method.
func (m *MockClient) Leases(ctx context.Context) (*clientv3.LeaseLeasesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Leases", ctx)
	ret0, _ := ret[0].(*clientv3.LeaseLeasesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Leases indicates an expected call of Leases.
func (mr *MockClientMockRecorder) Leases(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Leases", reflect.TypeOf((*MockClient)(nil).Leases), ctx)
}

// MemberAdd mocks base method.
func (m *MockClient) MemberAdd(ctx context.Context, peerAddrs []string) (*clientv3.MemberAddResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MemberAdd", ctx, peerAddrs)
	ret0, _ := ret[0].(*clientv3.MemberAddResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MemberAdd indicates an expected call of MemberAdd.
func (mr *MockClientMockRecorder) MemberAdd(ctx, peerAddrs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MemberAdd", reflect.TypeOf((*MockClient)(nil).MemberAdd), ctx, peerAddrs)
}

// MemberAddAsLearner mocks base method.
func (m *MockClient) MemberAddAsLearner(ctx context.Context, peerAddrs []string) (*clientv3.MemberAddResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MemberAddAsLearner", ctx, peerAddrs)
	ret0, _ := ret[0].(*clientv3.MemberAddResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MemberAddAsLearner indicates an expected call of MemberAddAsLearner.
func (mr *MockClientMockRecorder) MemberAddAsLearner(ctx, peerAddrs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MemberAddAsLearner", reflect.TypeOf((*MockClient)(nil).MemberAddAsLearner), ctx, peerAddrs)
}

// MemberList mocks base method.
func (m *MockClient) MemberList(ctx context.Context) (*clientv3.MemberListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MemberList", ctx)
	ret0, _ := ret[0].(*clientv3.MemberListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MemberList indicates an expected call of MemberList.
func (mr *MockClientMockRecorder) MemberList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MemberList", reflect.TypeOf((*MockClient)(nil).MemberList), ctx)
}

// MemberPromote mocks base method.
func (m *MockClient) MemberPromote(ctx context.Context, id uint64) (*clientv3.MemberPromoteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MemberPromote", ctx, id)
	ret0, _ := ret[0].(*clientv3.MemberPromoteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MemberPromote indicates an expected call of MemberPromote.
func (mr *MockClientMockRecorder) MemberPromote(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MemberPromote", reflect.TypeOf((*MockClient)(nil).MemberPromote), ctx, id)
}

// MemberRemove mocks base method.
func (m *MockClient) MemberRemove(ctx context.Context, id uint64) (*clientv3.MemberRemoveResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MemberRemove", ctx, id)
	ret0, _ := ret[0].(*clientv3.MemberRemoveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MemberRemove indicates an expected call of MemberRemove.
func (mr *MockClientMockRecorder) MemberRemove(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MemberRemove", reflect.TypeOf((*MockClient)(nil).MemberRemove), ctx, id)
}

// MemberUpdate mocks base method.
func (m *MockClient) MemberUpdate(ctx context.Context, id uint64, peerAddrs []string) (*clientv3.MemberUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MemberUpdate", ctx, id, peerAddrs)
	ret0, _ := ret[0].(*clientv3.MemberUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MemberUpdate indicates an expected call of MemberUpdate.
func (mr *MockClientMockRecorder) MemberUpdate(ctx, id, peerAddrs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MemberUpdate", reflect.TypeOf((*MockClient)(nil).MemberUpdate), ctx, id, peerAddrs)
}

// MoveLeader mocks base method.
func (m *MockClient) MoveLeader(ctx context.Context, transfereeID uint64) (*clientv3.MoveLeaderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MoveLeader", ctx, transfereeID)
	ret0, _ := ret[0].(*clientv3.MoveLeaderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MoveLeader indicates an expected call of MoveLeader.
func (mr *MockClientMockRecorder) MoveLeader(ctx, transfereeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveLeader", reflect.TypeOf((*MockClient)(nil).MoveLeader), ctx, transfereeID)
}

// Put mocks base method.
func (m *MockClient) Put(ctx context.Context, key, val string, opts ...clientv3.OpOption) (*clientv3.PutResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key, val}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Put", varargs...)
	ret0, _ := ret[0].(*clientv3.PutResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockClientMockRecorder) Put(ctx, key, val any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key, val}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockClient)(nil).Put), varargs...)
}

// RequestProgress mocks base method.
func (m *MockClient) RequestProgress(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestProgress", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestProgress indicates an expected call of RequestProgress.
func (mr *MockClientMockRecorder) RequestProgress(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestProgress", reflect.TypeOf((*MockClient)(nil).RequestProgress), ctx)
}

// Revoke mocks base method.
func (m *MockClient) Revoke(ctx context.Context, id clientv3.LeaseID) (*clientv3.LeaseRevokeResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id)
	ret0, _ := ret[0].(*clientv3.LeaseRevokeResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Revoke indicates an expected call of Revoke.
func (mr *MockClientMockRecorder) Revoke(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockClient)(nil).Revoke), ctx, id)
}

// RoleAdd mocks base method.
func (m *MockClient) RoleAdd(ctx context.Context, name string) (*clientv3.AuthRoleAddResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleAdd", ctx, name)
	ret0, _ := ret[0].(*clientv3.AuthRoleAddResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoleAdd indicates an expected call of RoleAdd.
func (mr *MockClientMockRecorder) RoleAdd(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleAdd", reflect.TypeOf((*MockClient)(nil).RoleAdd), ctx, name)
}

// RoleDelete mocks base method.
func (m *MockClient) RoleDelete(ctx context.Context, role string) (*clientv3.AuthRoleDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleDelete", ctx, role)
	ret0, _ := ret[0].(*clientv3.AuthRoleDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoleDelete indicates an expected call of RoleDelete.
func (mr *MockClientMockRecorder) RoleDelete(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleDelete", reflect.TypeOf((*MockClient)(nil).RoleDelete), ctx, role)
}

// RoleGet mocks base method.
func (m *MockClient) RoleGet(ctx context.Context, role string) (*clientv3.AuthRoleGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleGet", ctx, role)
	ret0, _ := ret[0].(*clientv3.AuthRoleGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoleGet indicates an expected call of RoleGet.
func (mr *MockClientMockRecorder) RoleGet(ctx, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleGet", reflect.TypeOf((*MockClient)(nil).RoleGet), ctx, role)
}

// RoleGrantPermission mocks base method.
func (m *MockClient) RoleGrantPermission(ctx context.Context, name, key, rangeEnd string, permType clientv3.PermissionType) (*clientv3.AuthRoleGrantPermissionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleGrantPermission", ctx, name, key, rangeEnd, permType)
	ret0, _ := ret[0].(*clientv3.AuthRoleGrantPermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoleGrantPermission indicates an expected call of RoleGrantPermission.
func (mr *MockClientMockRecorder) RoleGrantPermission(ctx, name, key, rangeEnd, permType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleGrantPermission", reflect.TypeOf((*MockClient)(nil).RoleGrantPermission), ctx, name, key, rangeEnd, permType)
}

// RoleList mocks base method.
func (m *MockClient) RoleList(ctx context.Context) (*clientv3.AuthRoleListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleList", ctx)
	ret0, _ := ret[0].(*clientv3.AuthRoleListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoleList indicates an expected call of RoleList.
func (mr *MockClientMockRecorder) RoleList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleList", reflect.TypeOf((*MockClient)(nil).RoleList), ctx)
}

// RoleRevokePermission mocks base method.
func (m *MockClient) RoleRevokePermission(ctx context.Context, role, key, rangeEnd string) (*clientv3.AuthRoleRevokePermissionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoleRevokePermission", ctx, role, key, rangeEnd)
	ret0, _ := ret[0].(*clientv3.AuthRoleRevokePermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoleRevokePermission indicates an expected call of RoleRevokePermission.
func (mr *MockClientMockRecorder) RoleRevokePermission(ctx, role, key, rangeEnd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoleRevokePermission", reflect.TypeOf((*MockClient)(nil).RoleRevokePermission), ctx, role, key, rangeEnd)
}

// Snapshot mocks base method.
func (m *MockClient) Snapshot(ctx context.Context) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", ctx)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockClientMockRecorder) Snapshot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockClient)(nil).Snapshot), ctx)
}

// Status mocks base method.
func (m *MockClient) Status(ctx context.Context, endpoint string) (*clientv3.StatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, endpoint)
	ret0, _ := ret[0].(*clientv3.StatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockClientMockRecorder) Status(ctx, endpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockClient)(nil).Status), ctx, endpoint)
}

// TimeToLive mocks base method.
func (m *MockClient) TimeToLive(ctx context.Context, id clientv3.LeaseID, opts ...clientv3.LeaseOption) (*clientv3.LeaseTimeToLiveResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, id}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TimeToLive", varargs...)
	ret0, _ := ret[0].(*clientv3.LeaseTimeToLiveResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TimeToLive indicates an expected call of TimeToLive.
func (mr *MockClientMockRecorder) TimeToLive(ctx, id any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, id}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TimeToLive", reflect.TypeOf((*MockClient)(nil).TimeToLive), varargs...)
}

// Txn mocks base method.
func (m *MockClient) Txn(ctx context.Context) clientv3.Txn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Txn", ctx)
	ret0, _ := ret[0].(clientv3.Txn)
	return ret0
}

// Txn indicates an expected call of Txn.
func (mr *MockClientMockRecorder) Txn(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Txn", reflect.TypeOf((*MockClient)(nil).Txn), ctx)
}

// UserAdd mocks base method.
func (m *MockClient) UserAdd(ctx context.Context, name, password string) (*clientv3.AuthUserAddResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserAdd", ctx, name, password)
	ret0, _ := ret[0].(*clientv3.AuthUserAddResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserAdd indicates an expected call of UserAdd.
func (mr *MockClientMockRecorder) UserAdd(ctx, name, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserAdd", reflect.TypeOf((*MockClient)(nil).UserAdd), ctx, name, password)
}

// UserAddWithOptions mocks base method.
func (m *MockClient) UserAddWithOptions(ctx context.Context, name, password string, opt *clientv3.UserAddOptions) (*clientv3.AuthUserAddResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserAddWithOptions", ctx, name, password, opt)
	ret0, _ := ret[0].(*clientv3.AuthUserAddResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserAddWithOptions indicates an expected call of UserAddWithOptions.
func (mr *MockClientMockRecorder) UserAddWithOptions(ctx, name, password, opt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserAddWithOptions", reflect.TypeOf((*MockClient)(nil).UserAddWithOptions), ctx, name, password, opt)
}

// UserChangePassword mocks base method.
func (m *MockClient) UserChangePassword(ctx context.Context, name, password string) (*clientv3.AuthUserChangePasswordResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserChangePassword", ctx, name, password)
	ret0, _ := ret[0].(*clientv3.AuthUserChangePasswordResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserChangePassword indicates an expected call of UserChangePassword.
func (mr *MockClientMockRecorder) UserChangePassword(ctx, name, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserChangePassword", reflect.TypeOf((*MockClient)(nil).UserChangePassword), ctx, name, password)
}

// UserDelete mocks base method.
func (m *MockClient) UserDelete(ctx context.Context, name string) (*clientv3.AuthUserDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserDelete", ctx, name)
	ret0, _ := ret[0].(*clientv3.AuthUserDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserDelete indicates an expected call of UserDelete.
func (mr *MockClientMockRecorder) UserDelete(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserDelete", reflect.TypeOf((*MockClient)(nil).UserDelete), ctx, name)
}

// UserGet mocks base method.
func (m *MockClient) UserGet(ctx context.Context, name string) (*clientv3.AuthUserGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserGet", ctx, name)
	ret0, _ := ret[0].(*clientv3.AuthUserGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserGet indicates an expected call of UserGet.
func (mr *MockClientMockRecorder) UserGet(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserGet", reflect.TypeOf((*MockClient)(nil).UserGet), ctx, name)
}

// UserGrantRole mocks base method.
func (m *MockClient) UserGrantRole(ctx context.Context, user, role string) (*clientv3.AuthUserGrantRoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserGrantRole", ctx, user, role)
	ret0, _ := ret[0].(*clientv3.AuthUserGrantRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserGrantRole indicates an expected call of UserGrantRole.
func (mr *MockClientMockRecorder) UserGrantRole(ctx, user, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserGrantRole", reflect.TypeOf((*MockClient)(nil).UserGrantRole), ctx, user, role)
}

// UserList mocks base method.
func (m *MockClient) UserList(ctx context.Context) (*clientv3.AuthUserListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserList", ctx)
	ret0, _ := ret[0].(*clientv3.AuthUserListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserList indicates an expected call of UserList.
func (mr *MockClientMockRecorder) UserList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserList", reflect.TypeOf((*MockClient)(nil).UserList), ctx)
}

// UserRevokeRole mocks base method.
func (m *MockClient) UserRevokeRole(ctx context.Context, name, role string) (*clientv3.AuthUserRevokeRoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserRevokeRole", ctx, name, role)
	ret0, _ := ret[0].(*clientv3.AuthUserRevokeRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserRevokeRole indicates an expected call of UserRevokeRole.
func (mr *MockClientMockRecorder) UserRevokeRole(ctx, name, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserRevokeRole", reflect.TypeOf((*MockClient)(nil).UserRevokeRole), ctx, name, role)
}

// Watch mocks base method.
func (m *MockClient) Watch(ctx context.Context, key string, opts ...clientv3.OpOption) clientv3.WatchChan {
	m.ctrl.T.Helper()
	varargs := []any{ctx, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Watch", varargs...)
	ret0, _ := ret[0].(clientv3.WatchChan)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockClientMockRecorder) Watch(ctx, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockClient)(nil).Watch), varargs...)
}
