package ratelimited

// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

import (
	"context"

	"github.com/uber/cadence/common/metrics"
	"github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
)

// ratelimitedDomainManager implements persistence.DomainManager interface instrumented with rate limiter.
type ratelimitedDomainManager struct {
	wrapped       persistence.DomainManager
	rateLimiter   quotas.Limiter
	metricsClient metrics.Client
	datastoreName string
}

// NewDomainManager creates a new instance of DomainManager with ratelimiter.
func NewDomainManager(
	wrapped persistence.DomainManager,
	rateLimiter quotas.Limiter,
	metricsClient metrics.Client,
	datastoreName string,
) persistence.DomainManager {
	return &ratelimitedDomainManager{
		wrapped:       wrapped,
		rateLimiter:   rateLimiter,
		metricsClient: metricsClient,
		datastoreName: datastoreName,
	}
}

func (c *ratelimitedDomainManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedDomainManager) CreateDomain(ctx context.Context, request *persistence.CreateDomainRequest) (cp1 *persistence.CreateDomainResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CreateDomain(ctx, request)
}

func (c *ratelimitedDomainManager) DeleteDomain(ctx context.Context, request *persistence.DeleteDomainRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteDomain(ctx, request)
}

func (c *ratelimitedDomainManager) DeleteDomainByName(ctx context.Context, request *persistence.DeleteDomainByNameRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteDomainByName(ctx, request)
}

func (c *ratelimitedDomainManager) GetDomain(ctx context.Context, request *persistence.GetDomainRequest) (gp1 *persistence.GetDomainResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetDomain(ctx, request)
}

func (c *ratelimitedDomainManager) GetMetadata(ctx context.Context) (gp1 *persistence.GetMetadataResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetMetadata(ctx)
}

func (c *ratelimitedDomainManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *ratelimitedDomainManager) ListDomains(ctx context.Context, request *persistence.ListDomainsRequest) (lp1 *persistence.ListDomainsResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListDomains(ctx, request)
}

func (c *ratelimitedDomainManager) UpdateDomain(ctx context.Context, request *persistence.UpdateDomainRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpdateDomain(ctx, request)
}
