package ratelimited

// Code generated by gowrap. DO NOT EDIT.
// template: ../templates/ratelimited.tmpl
// gowrap: http://github.com/hexdigest/gowrap

import (
	"context"

	"github.com/uber/cadence/common/metrics"
	"github.com/uber/cadence/common/persistence"
	"github.com/uber/cadence/common/quotas"
)

// ratelimitedTaskManager implements persistence.TaskManager interface instrumented with rate limiter.
type ratelimitedTaskManager struct {
	wrapped       persistence.TaskManager
	rateLimiter   quotas.Limiter
	metricsClient metrics.Client
	datastoreName string
}

// NewTaskManager creates a new instance of TaskManager with ratelimiter.
func NewTaskManager(
	wrapped persistence.TaskManager,
	rateLimiter quotas.Limiter,
	metricsClient metrics.Client,
	datastoreName string,
) persistence.TaskManager {
	return &ratelimitedTaskManager{
		wrapped:       wrapped,
		rateLimiter:   rateLimiter,
		metricsClient: metricsClient,
		datastoreName: datastoreName,
	}
}

func (c *ratelimitedTaskManager) Close() {
	c.wrapped.Close()
	return
}

func (c *ratelimitedTaskManager) CompleteTask(ctx context.Context, request *persistence.CompleteTaskRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CompleteTask(ctx, request)
}

func (c *ratelimitedTaskManager) CompleteTasksLessThan(ctx context.Context, request *persistence.CompleteTasksLessThanRequest) (cp1 *persistence.CompleteTasksLessThanResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CompleteTasksLessThan(ctx, request)
}

func (c *ratelimitedTaskManager) CreateTasks(ctx context.Context, request *persistence.CreateTasksRequest) (cp1 *persistence.CreateTasksResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.CreateTasks(ctx, request)
}

func (c *ratelimitedTaskManager) DeleteTaskList(ctx context.Context, request *persistence.DeleteTaskListRequest) (err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.DeleteTaskList(ctx, request)
}

func (c *ratelimitedTaskManager) GetName() (s1 string) {
	return c.wrapped.GetName()
}

func (c *ratelimitedTaskManager) GetOrphanTasks(ctx context.Context, request *persistence.GetOrphanTasksRequest) (gp1 *persistence.GetOrphanTasksResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetOrphanTasks(ctx, request)
}

func (c *ratelimitedTaskManager) GetTaskList(ctx context.Context, request *persistence.GetTaskListRequest) (gp1 *persistence.GetTaskListResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetTaskList(ctx, request)
}

func (c *ratelimitedTaskManager) GetTaskListSize(ctx context.Context, request *persistence.GetTaskListSizeRequest) (gp1 *persistence.GetTaskListSizeResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetTaskListSize(ctx, request)
}

func (c *ratelimitedTaskManager) GetTasks(ctx context.Context, request *persistence.GetTasksRequest) (gp1 *persistence.GetTasksResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.GetTasks(ctx, request)
}

func (c *ratelimitedTaskManager) LeaseTaskList(ctx context.Context, request *persistence.LeaseTaskListRequest) (lp1 *persistence.LeaseTaskListResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.LeaseTaskList(ctx, request)
}

func (c *ratelimitedTaskManager) ListTaskList(ctx context.Context, request *persistence.ListTaskListRequest) (lp1 *persistence.ListTaskListResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.ListTaskList(ctx, request)
}

func (c *ratelimitedTaskManager) UpdateTaskList(ctx context.Context, request *persistence.UpdateTaskListRequest) (up1 *persistence.UpdateTaskListResponse, err error) {
	if c.metricsClient != nil {
		scope := c.metricsClient.Scope(metrics.PersistenceCreateShardScope, metrics.DatastoreTag(c.datastoreName))
		scope.UpdateGauge(metrics.PersistenceQuota, float64(c.rateLimiter.Limit()))
	}
	if ok := c.rateLimiter.Allow(); !ok {
		err = ErrPersistenceLimitExceeded
		return
	}
	return c.wrapped.UpdateTaskList(ctx, request)
}
