// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: uber/cadence/sharddistributor/v1/canary.proto

package sharddistributorv1

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// ShardDistributorExecutorCanaryAPIYARPCClient is the YARPC client-side interface for the ShardDistributorExecutorCanaryAPI service.
type ShardDistributorExecutorCanaryAPIYARPCClient interface {
	Ping(context.Context, *PingRequest, ...yarpc.CallOption) (*PingResponse, error)
}

func newShardDistributorExecutorCanaryAPIYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) ShardDistributorExecutorCanaryAPIYARPCClient {
	return &_ShardDistributorExecutorCanaryAPIYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.cadence.sharddistributor.v1.ShardDistributorExecutorCanaryAPI",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewShardDistributorExecutorCanaryAPIYARPCClient builds a new YARPC client for the ShardDistributorExecutorCanaryAPI service.
func NewShardDistributorExecutorCanaryAPIYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) ShardDistributorExecutorCanaryAPIYARPCClient {
	return newShardDistributorExecutorCanaryAPIYARPCClient(clientConfig, nil, options...)
}

// ShardDistributorExecutorCanaryAPIYARPCServer is the YARPC server-side interface for the ShardDistributorExecutorCanaryAPI service.
type ShardDistributorExecutorCanaryAPIYARPCServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

type buildShardDistributorExecutorCanaryAPIYARPCProceduresParams struct {
	Server      ShardDistributorExecutorCanaryAPIYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildShardDistributorExecutorCanaryAPIYARPCProcedures(params buildShardDistributorExecutorCanaryAPIYARPCProceduresParams) []transport.Procedure {
	handler := &_ShardDistributorExecutorCanaryAPIYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName: "uber.cadence.sharddistributor.v1.ShardDistributorExecutorCanaryAPI",
			UnaryHandlerParams: []protobuf.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "Ping",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.Ping,
							NewRequest:  newShardDistributorExecutorCanaryAPIServicePingYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildShardDistributorExecutorCanaryAPIYARPCProcedures prepares an implementation of the ShardDistributorExecutorCanaryAPI service for YARPC registration.
func BuildShardDistributorExecutorCanaryAPIYARPCProcedures(server ShardDistributorExecutorCanaryAPIYARPCServer) []transport.Procedure {
	return buildShardDistributorExecutorCanaryAPIYARPCProcedures(buildShardDistributorExecutorCanaryAPIYARPCProceduresParams{Server: server})
}

// FxShardDistributorExecutorCanaryAPIYARPCClientParams defines the input
// for NewFxShardDistributorExecutorCanaryAPIYARPCClient. It provides the
// paramaters to get a ShardDistributorExecutorCanaryAPIYARPCClient in an
// Fx application.
type FxShardDistributorExecutorCanaryAPIYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxShardDistributorExecutorCanaryAPIYARPCClientResult defines the output
// of NewFxShardDistributorExecutorCanaryAPIYARPCClient. It provides a
// ShardDistributorExecutorCanaryAPIYARPCClient to an Fx application.
type FxShardDistributorExecutorCanaryAPIYARPCClientResult struct {
	fx.Out

	Client ShardDistributorExecutorCanaryAPIYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxShardDistributorExecutorCanaryAPIYARPCClient provides a ShardDistributorExecutorCanaryAPIYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorExecutorCanaryAPIYARPCClient("service-name"),
//	  ...
//	)
func NewFxShardDistributorExecutorCanaryAPIYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxShardDistributorExecutorCanaryAPIYARPCClientParams) FxShardDistributorExecutorCanaryAPIYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxShardDistributorExecutorCanaryAPIYARPCClientResult{
			Client: newShardDistributorExecutorCanaryAPIYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxShardDistributorExecutorCanaryAPIYARPCProceduresParams defines the input
// for NewFxShardDistributorExecutorCanaryAPIYARPCProcedures. It provides the
// paramaters to get ShardDistributorExecutorCanaryAPIYARPCServer procedures in an
// Fx application.
type FxShardDistributorExecutorCanaryAPIYARPCProceduresParams struct {
	fx.In

	Server      ShardDistributorExecutorCanaryAPIYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxShardDistributorExecutorCanaryAPIYARPCProceduresResult defines the output
// of NewFxShardDistributorExecutorCanaryAPIYARPCProcedures. It provides
// ShardDistributorExecutorCanaryAPIYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxShardDistributorExecutorCanaryAPIYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxShardDistributorExecutorCanaryAPIYARPCProcedures provides ShardDistributorExecutorCanaryAPIYARPCServer procedures to an Fx application.
// It expects a ShardDistributorExecutorCanaryAPIYARPCServer to be present in the container.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorExecutorCanaryAPIYARPCProcedures(),
//	  ...
//	)
func NewFxShardDistributorExecutorCanaryAPIYARPCProcedures() interface{} {
	return func(params FxShardDistributorExecutorCanaryAPIYARPCProceduresParams) FxShardDistributorExecutorCanaryAPIYARPCProceduresResult {
		return FxShardDistributorExecutorCanaryAPIYARPCProceduresResult{
			Procedures: buildShardDistributorExecutorCanaryAPIYARPCProcedures(buildShardDistributorExecutorCanaryAPIYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: ShardDistributorExecutorCanaryAPIReflectionMeta,
		}
	}
}

// ShardDistributorExecutorCanaryAPIReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var ShardDistributorExecutorCanaryAPIReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.cadence.sharddistributor.v1.ShardDistributorExecutorCanaryAPI",
	FileDescriptors: yarpcFileDescriptorClosure03b11524fa4f4f94,
}

type _ShardDistributorExecutorCanaryAPIYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_ShardDistributorExecutorCanaryAPIYARPCCaller) Ping(ctx context.Context, request *PingRequest, options ...yarpc.CallOption) (*PingResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Ping", request, newShardDistributorExecutorCanaryAPIServicePingYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*PingResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorExecutorCanaryAPIServicePingYARPCResponse, responseMessage)
	}
	return response, err
}

type _ShardDistributorExecutorCanaryAPIYARPCHandler struct {
	server ShardDistributorExecutorCanaryAPIYARPCServer
}

func (h *_ShardDistributorExecutorCanaryAPIYARPCHandler) Ping(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *PingRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*PingRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorExecutorCanaryAPIServicePingYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Ping(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newShardDistributorExecutorCanaryAPIServicePingYARPCRequest() proto.Message {
	return &PingRequest{}
}

func newShardDistributorExecutorCanaryAPIServicePingYARPCResponse() proto.Message {
	return &PingResponse{}
}

var (
	emptyShardDistributorExecutorCanaryAPIServicePingYARPCRequest  = &PingRequest{}
	emptyShardDistributorExecutorCanaryAPIServicePingYARPCResponse = &PingResponse{}
)

var yarpcFileDescriptorClosure03b11524fa4f4f94 = [][]byte{
	// uber/cadence/sharddistributor/v1/canary.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xbd, 0x4e, 0xf3, 0x30,
		0x14, 0x86, 0x95, 0xef, 0x43, 0xa8, 0x39, 0x65, 0xf2, 0x54, 0xf1, 0x23, 0x4a, 0x27, 0x96, 0xda,
		0x0a, 0x8c, 0x4c, 0xfc, 0x49, 0x44, 0x5d, 0xaa, 0xb0, 0xb1, 0x44, 0x8e, 0x73, 0x94, 0x5a, 0x55,
		0xed, 0x60, 0x3b, 0x81, 0xdc, 0x02, 0x57, 0x8d, 0xec, 0x06, 0x95, 0x54, 0x48, 0xb0, 0x3e, 0x7e,
		0xf4, 0xfa, 0x9c, 0xf3, 0xc2, 0xbc, 0x29, 0xd0, 0x30, 0xc1, 0x4b, 0x54, 0x02, 0x99, 0x5d, 0x71,
		0x53, 0x96, 0xd2, 0x3a, 0x23, 0x8b, 0xc6, 0x69, 0xc3, 0xda, 0x84, 0x09, 0xae, 0xb8, 0xe9, 0x68,
		0x6d, 0xb4, 0xd3, 0x64, 0xea, 0x75, 0xda, 0xeb, 0x74, 0x5f, 0xa7, 0x6d, 0x32, 0x7b, 0x82, 0xf1,
		0x52, 0xaa, 0x2a, 0xc3, 0xd7, 0x06, 0xad, 0x23, 0x27, 0x10, 0x07, 0x2b, 0x5f, 0x63, 0x37, 0x89,
		0xa6, 0xd1, 0x65, 0x9c, 0x8d, 0x02, 0x58, 0x60, 0x47, 0x4e, 0x21, 0x56, 0x7c, 0x83, 0xb6, 0xe6,
		0x02, 0x27, 0xff, 0xc2, 0xe3, 0x0e, 0xcc, 0xd6, 0x70, 0xb4, 0x4d, 0xb2, 0xb5, 0x56, 0x16, 0xc9,
		0x39, 0x8c, 0xf1, 0x1d, 0x85, 0xff, 0x28, 0x97, 0x65, 0x1f, 0x06, 0x5f, 0x28, 0x2d, 0xc9, 0x19,
		0x80, 0x7e, 0x53, 0x36, 0x0f, 0xf9, 0x21, 0x6f, 0x94, 0xc5, 0x9e, 0x3c, 0x7b, 0x30, 0x1c, 0xe5,
		0xff, 0x70, 0x94, 0xab, 0x8f, 0x08, 0x2e, 0x82, 0xf6, 0xb0, 0x5b, 0xe7, 0xb1, 0x8f, 0xbe, 0x0f,
		0x17, 0xb8, 0x5d, 0xa6, 0x04, 0xe1, 0xc0, 0x8f, 0x44, 0xe6, 0xf4, 0xb7, 0x3b, 0xd0, 0x6f, 0x47,
		0x38, 0xa6, 0x7f, 0xd5, 0xb7, 0x9b, 0xde, 0x2d, 0x5e, 0xd2, 0x4a, 0xba, 0x55, 0x53, 0x50, 0xa1,
		0x37, 0x6c, 0xd0, 0x10, 0xad, 0x50, 0xb1, 0xd0, 0xc5, 0x4f, 0x65, 0xdd, 0xec, 0xb3, 0x36, 0x29,
		0x0e, 0x83, 0x7d, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x61, 0x98, 0x91, 0xea, 0x01, 0x00,
		0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) ShardDistributorExecutorCanaryAPIYARPCClient {
			return NewShardDistributorExecutorCanaryAPIYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
