// Code generated by MockGen. DO NOT EDIT.
// Source: etcdstore.go
//
// Generated by this command:
//
//	mockgen -package executorstore -source etcdstore.go -destination=executorstore_mock.go ExecutorStore
//

// Package executorstore is a generated GoMock package.
package executorstore
