// Code generated by "enumer -type=ExecutorStatus,ShardStatus,AssignmentStatus,MigrationMode,HandoverType,LoadBalancingMode -json -output sharddistributor_statuses_enumer_generated.go"; DO NOT EDIT.

package types

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ExecutorStatusName = "ExecutorStatusINVALIDExecutorStatusACTIVEExecutorStatusDRAININGExecutorStatusDRAINED"

var _ExecutorStatusIndex = [...]uint8{0, 21, 41, 63, 84}

const _ExecutorStatusLowerName = "executorstatusinvalidexecutorstatusactiveexecutorstatusdrainingexecutorstatusdrained"

func (i ExecutorStatus) String() string {
	if i < 0 || i >= ExecutorStatus(len(_ExecutorStatusIndex)-1) {
		return fmt.Sprintf("ExecutorStatus(%d)", i)
	}
	return _ExecutorStatusName[_ExecutorStatusIndex[i]:_ExecutorStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ExecutorStatusNoOp() {
	var x [1]struct{}
	_ = x[ExecutorStatusINVALID-(0)]
	_ = x[ExecutorStatusACTIVE-(1)]
	_ = x[ExecutorStatusDRAINING-(2)]
	_ = x[ExecutorStatusDRAINED-(3)]
}

var _ExecutorStatusValues = []ExecutorStatus{ExecutorStatusINVALID, ExecutorStatusACTIVE, ExecutorStatusDRAINING, ExecutorStatusDRAINED}

var _ExecutorStatusNameToValueMap = map[string]ExecutorStatus{
	_ExecutorStatusName[0:21]:       ExecutorStatusINVALID,
	_ExecutorStatusLowerName[0:21]:  ExecutorStatusINVALID,
	_ExecutorStatusName[21:41]:      ExecutorStatusACTIVE,
	_ExecutorStatusLowerName[21:41]: ExecutorStatusACTIVE,
	_ExecutorStatusName[41:63]:      ExecutorStatusDRAINING,
	_ExecutorStatusLowerName[41:63]: ExecutorStatusDRAINING,
	_ExecutorStatusName[63:84]:      ExecutorStatusDRAINED,
	_ExecutorStatusLowerName[63:84]: ExecutorStatusDRAINED,
}

var _ExecutorStatusNames = []string{
	_ExecutorStatusName[0:21],
	_ExecutorStatusName[21:41],
	_ExecutorStatusName[41:63],
	_ExecutorStatusName[63:84],
}

// ExecutorStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ExecutorStatusString(s string) (ExecutorStatus, error) {
	if val, ok := _ExecutorStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ExecutorStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ExecutorStatus values", s)
}

// ExecutorStatusValues returns all values of the enum
func ExecutorStatusValues() []ExecutorStatus {
	return _ExecutorStatusValues
}

// ExecutorStatusStrings returns a slice of all String values of the enum
func ExecutorStatusStrings() []string {
	strs := make([]string, len(_ExecutorStatusNames))
	copy(strs, _ExecutorStatusNames)
	return strs
}

// IsAExecutorStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ExecutorStatus) IsAExecutorStatus() bool {
	for _, v := range _ExecutorStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ExecutorStatus
func (i ExecutorStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ExecutorStatus
func (i *ExecutorStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ExecutorStatus should be a string, got %s", data)
	}

	var err error
	*i, err = ExecutorStatusString(s)
	return err
}

const _ShardStatusName = "ShardStatusINVALIDShardStatusREADYShardStatusDONE"

var _ShardStatusIndex = [...]uint8{0, 18, 34, 49}

const _ShardStatusLowerName = "shardstatusinvalidshardstatusreadyshardstatusdone"

func (i ShardStatus) String() string {
	if i < 0 || i >= ShardStatus(len(_ShardStatusIndex)-1) {
		return fmt.Sprintf("ShardStatus(%d)", i)
	}
	return _ShardStatusName[_ShardStatusIndex[i]:_ShardStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ShardStatusNoOp() {
	var x [1]struct{}
	_ = x[ShardStatusINVALID-(0)]
	_ = x[ShardStatusREADY-(1)]
	_ = x[ShardStatusDONE-(2)]
}

var _ShardStatusValues = []ShardStatus{ShardStatusINVALID, ShardStatusREADY, ShardStatusDONE}

var _ShardStatusNameToValueMap = map[string]ShardStatus{
	_ShardStatusName[0:18]:       ShardStatusINVALID,
	_ShardStatusLowerName[0:18]:  ShardStatusINVALID,
	_ShardStatusName[18:34]:      ShardStatusREADY,
	_ShardStatusLowerName[18:34]: ShardStatusREADY,
	_ShardStatusName[34:49]:      ShardStatusDONE,
	_ShardStatusLowerName[34:49]: ShardStatusDONE,
}

var _ShardStatusNames = []string{
	_ShardStatusName[0:18],
	_ShardStatusName[18:34],
	_ShardStatusName[34:49],
}

// ShardStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ShardStatusString(s string) (ShardStatus, error) {
	if val, ok := _ShardStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ShardStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ShardStatus values", s)
}

// ShardStatusValues returns all values of the enum
func ShardStatusValues() []ShardStatus {
	return _ShardStatusValues
}

// ShardStatusStrings returns a slice of all String values of the enum
func ShardStatusStrings() []string {
	strs := make([]string, len(_ShardStatusNames))
	copy(strs, _ShardStatusNames)
	return strs
}

// IsAShardStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ShardStatus) IsAShardStatus() bool {
	for _, v := range _ShardStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ShardStatus
func (i ShardStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ShardStatus
func (i *ShardStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ShardStatus should be a string, got %s", data)
	}

	var err error
	*i, err = ShardStatusString(s)
	return err
}

const _AssignmentStatusName = "AssignmentStatusINVALIDAssignmentStatusREADY"

var _AssignmentStatusIndex = [...]uint8{0, 23, 44}

const _AssignmentStatusLowerName = "assignmentstatusinvalidassignmentstatusready"

func (i AssignmentStatus) String() string {
	if i < 0 || i >= AssignmentStatus(len(_AssignmentStatusIndex)-1) {
		return fmt.Sprintf("AssignmentStatus(%d)", i)
	}
	return _AssignmentStatusName[_AssignmentStatusIndex[i]:_AssignmentStatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AssignmentStatusNoOp() {
	var x [1]struct{}
	_ = x[AssignmentStatusINVALID-(0)]
	_ = x[AssignmentStatusREADY-(1)]
}

var _AssignmentStatusValues = []AssignmentStatus{AssignmentStatusINVALID, AssignmentStatusREADY}

var _AssignmentStatusNameToValueMap = map[string]AssignmentStatus{
	_AssignmentStatusName[0:23]:       AssignmentStatusINVALID,
	_AssignmentStatusLowerName[0:23]:  AssignmentStatusINVALID,
	_AssignmentStatusName[23:44]:      AssignmentStatusREADY,
	_AssignmentStatusLowerName[23:44]: AssignmentStatusREADY,
}

var _AssignmentStatusNames = []string{
	_AssignmentStatusName[0:23],
	_AssignmentStatusName[23:44],
}

// AssignmentStatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AssignmentStatusString(s string) (AssignmentStatus, error) {
	if val, ok := _AssignmentStatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AssignmentStatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AssignmentStatus values", s)
}

// AssignmentStatusValues returns all values of the enum
func AssignmentStatusValues() []AssignmentStatus {
	return _AssignmentStatusValues
}

// AssignmentStatusStrings returns a slice of all String values of the enum
func AssignmentStatusStrings() []string {
	strs := make([]string, len(_AssignmentStatusNames))
	copy(strs, _AssignmentStatusNames)
	return strs
}

// IsAAssignmentStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AssignmentStatus) IsAAssignmentStatus() bool {
	for _, v := range _AssignmentStatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for AssignmentStatus
func (i AssignmentStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for AssignmentStatus
func (i *AssignmentStatus) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("AssignmentStatus should be a string, got %s", data)
	}

	var err error
	*i, err = AssignmentStatusString(s)
	return err
}

const _MigrationModeName = "MigrationModeINVALIDMigrationModeLOCALPASSTHROUGHMigrationModeLOCALPASSTHROUGHSHADOWMigrationModeDISTRIBUTEDPASSTHROUGHMigrationModeONBOARDED"

var _MigrationModeIndex = [...]uint8{0, 20, 49, 84, 119, 141}

const _MigrationModeLowerName = "migrationmodeinvalidmigrationmodelocalpassthroughmigrationmodelocalpassthroughshadowmigrationmodedistributedpassthroughmigrationmodeonboarded"

func (i MigrationMode) String() string {
	if i < 0 || i >= MigrationMode(len(_MigrationModeIndex)-1) {
		return fmt.Sprintf("MigrationMode(%d)", i)
	}
	return _MigrationModeName[_MigrationModeIndex[i]:_MigrationModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _MigrationModeNoOp() {
	var x [1]struct{}
	_ = x[MigrationModeINVALID-(0)]
	_ = x[MigrationModeLOCALPASSTHROUGH-(1)]
	_ = x[MigrationModeLOCALPASSTHROUGHSHADOW-(2)]
	_ = x[MigrationModeDISTRIBUTEDPASSTHROUGH-(3)]
	_ = x[MigrationModeONBOARDED-(4)]
}

var _MigrationModeValues = []MigrationMode{MigrationModeINVALID, MigrationModeLOCALPASSTHROUGH, MigrationModeLOCALPASSTHROUGHSHADOW, MigrationModeDISTRIBUTEDPASSTHROUGH, MigrationModeONBOARDED}

var _MigrationModeNameToValueMap = map[string]MigrationMode{
	_MigrationModeName[0:20]:         MigrationModeINVALID,
	_MigrationModeLowerName[0:20]:    MigrationModeINVALID,
	_MigrationModeName[20:49]:        MigrationModeLOCALPASSTHROUGH,
	_MigrationModeLowerName[20:49]:   MigrationModeLOCALPASSTHROUGH,
	_MigrationModeName[49:84]:        MigrationModeLOCALPASSTHROUGHSHADOW,
	_MigrationModeLowerName[49:84]:   MigrationModeLOCALPASSTHROUGHSHADOW,
	_MigrationModeName[84:119]:       MigrationModeDISTRIBUTEDPASSTHROUGH,
	_MigrationModeLowerName[84:119]:  MigrationModeDISTRIBUTEDPASSTHROUGH,
	_MigrationModeName[119:141]:      MigrationModeONBOARDED,
	_MigrationModeLowerName[119:141]: MigrationModeONBOARDED,
}

var _MigrationModeNames = []string{
	_MigrationModeName[0:20],
	_MigrationModeName[20:49],
	_MigrationModeName[49:84],
	_MigrationModeName[84:119],
	_MigrationModeName[119:141],
}

// MigrationModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MigrationModeString(s string) (MigrationMode, error) {
	if val, ok := _MigrationModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _MigrationModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MigrationMode values", s)
}

// MigrationModeValues returns all values of the enum
func MigrationModeValues() []MigrationMode {
	return _MigrationModeValues
}

// MigrationModeStrings returns a slice of all String values of the enum
func MigrationModeStrings() []string {
	strs := make([]string, len(_MigrationModeNames))
	copy(strs, _MigrationModeNames)
	return strs
}

// IsAMigrationMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MigrationMode) IsAMigrationMode() bool {
	for _, v := range _MigrationModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for MigrationMode
func (i MigrationMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for MigrationMode
func (i *MigrationMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("MigrationMode should be a string, got %s", data)
	}

	var err error
	*i, err = MigrationModeString(s)
	return err
}

const _HandoverTypeName = "HandoverTypeINVALIDHandoverTypeGRACEFULHandoverTypeEMERGENCY"

var _HandoverTypeIndex = [...]uint8{0, 19, 39, 60}

const _HandoverTypeLowerName = "handovertypeinvalidhandovertypegracefulhandovertypeemergency"

func (i HandoverType) String() string {
	if i < 0 || i >= HandoverType(len(_HandoverTypeIndex)-1) {
		return fmt.Sprintf("HandoverType(%d)", i)
	}
	return _HandoverTypeName[_HandoverTypeIndex[i]:_HandoverTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _HandoverTypeNoOp() {
	var x [1]struct{}
	_ = x[HandoverTypeINVALID-(0)]
	_ = x[HandoverTypeGRACEFUL-(1)]
	_ = x[HandoverTypeEMERGENCY-(2)]
}

var _HandoverTypeValues = []HandoverType{HandoverTypeINVALID, HandoverTypeGRACEFUL, HandoverTypeEMERGENCY}

var _HandoverTypeNameToValueMap = map[string]HandoverType{
	_HandoverTypeName[0:19]:       HandoverTypeINVALID,
	_HandoverTypeLowerName[0:19]:  HandoverTypeINVALID,
	_HandoverTypeName[19:39]:      HandoverTypeGRACEFUL,
	_HandoverTypeLowerName[19:39]: HandoverTypeGRACEFUL,
	_HandoverTypeName[39:60]:      HandoverTypeEMERGENCY,
	_HandoverTypeLowerName[39:60]: HandoverTypeEMERGENCY,
}

var _HandoverTypeNames = []string{
	_HandoverTypeName[0:19],
	_HandoverTypeName[19:39],
	_HandoverTypeName[39:60],
}

// HandoverTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func HandoverTypeString(s string) (HandoverType, error) {
	if val, ok := _HandoverTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _HandoverTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to HandoverType values", s)
}

// HandoverTypeValues returns all values of the enum
func HandoverTypeValues() []HandoverType {
	return _HandoverTypeValues
}

// HandoverTypeStrings returns a slice of all String values of the enum
func HandoverTypeStrings() []string {
	strs := make([]string, len(_HandoverTypeNames))
	copy(strs, _HandoverTypeNames)
	return strs
}

// IsAHandoverType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i HandoverType) IsAHandoverType() bool {
	for _, v := range _HandoverTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for HandoverType
func (i HandoverType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for HandoverType
func (i *HandoverType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("HandoverType should be a string, got %s", data)
	}

	var err error
	*i, err = HandoverTypeString(s)
	return err
}

const _LoadBalancingModeName = "LoadBalancingModeINVALIDLoadBalancingModeNAIVELoadBalancingModeGREEDY"

var _LoadBalancingModeIndex = [...]uint8{0, 24, 46, 69}

const _LoadBalancingModeLowerName = "loadbalancingmodeinvalidloadbalancingmodenaiveloadbalancingmodegreedy"

func (i LoadBalancingMode) String() string {
	if i < 0 || i >= LoadBalancingMode(len(_LoadBalancingModeIndex)-1) {
		return fmt.Sprintf("LoadBalancingMode(%d)", i)
	}
	return _LoadBalancingModeName[_LoadBalancingModeIndex[i]:_LoadBalancingModeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _LoadBalancingModeNoOp() {
	var x [1]struct{}
	_ = x[LoadBalancingModeINVALID-(0)]
	_ = x[LoadBalancingModeNAIVE-(1)]
	_ = x[LoadBalancingModeGREEDY-(2)]
}

var _LoadBalancingModeValues = []LoadBalancingMode{LoadBalancingModeINVALID, LoadBalancingModeNAIVE, LoadBalancingModeGREEDY}

var _LoadBalancingModeNameToValueMap = map[string]LoadBalancingMode{
	_LoadBalancingModeName[0:24]:       LoadBalancingModeINVALID,
	_LoadBalancingModeLowerName[0:24]:  LoadBalancingModeINVALID,
	_LoadBalancingModeName[24:46]:      LoadBalancingModeNAIVE,
	_LoadBalancingModeLowerName[24:46]: LoadBalancingModeNAIVE,
	_LoadBalancingModeName[46:69]:      LoadBalancingModeGREEDY,
	_LoadBalancingModeLowerName[46:69]: LoadBalancingModeGREEDY,
}

var _LoadBalancingModeNames = []string{
	_LoadBalancingModeName[0:24],
	_LoadBalancingModeName[24:46],
	_LoadBalancingModeName[46:69],
}

// LoadBalancingModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func LoadBalancingModeString(s string) (LoadBalancingMode, error) {
	if val, ok := _LoadBalancingModeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _LoadBalancingModeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to LoadBalancingMode values", s)
}

// LoadBalancingModeValues returns all values of the enum
func LoadBalancingModeValues() []LoadBalancingMode {
	return _LoadBalancingModeValues
}

// LoadBalancingModeStrings returns a slice of all String values of the enum
func LoadBalancingModeStrings() []string {
	strs := make([]string, len(_LoadBalancingModeNames))
	copy(strs, _LoadBalancingModeNames)
	return strs
}

// IsALoadBalancingMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i LoadBalancingMode) IsALoadBalancingMode() bool {
	for _, v := range _LoadBalancingModeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for LoadBalancingMode
func (i LoadBalancingMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for LoadBalancingMode
func (i *LoadBalancingMode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("LoadBalancingMode should be a string, got %s", data)
	}

	var err error
	*i, err = LoadBalancingModeString(s)
	return err
}
