// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/cadence/.gen/proto/sharddistributor/v1 (interfaces: ShardDistributorExecutorAPIYARPCClient)
//
// Generated by this command:
//
//	mockgen -package executorclient -destination yarpc_client_mock.go github.com/uber/cadence/.gen/proto/sharddistributor/v1 ShardDistributorExecutorAPIYARPCClient
//

// Package executorclient is a generated GoMock package.
package executorclient

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	yarpc "go.uber.org/yarpc"

	sharddistributorv1 "github.com/uber/cadence/.gen/proto/sharddistributor/v1"
)

// MockShardDistributorExecutorAPIYARPCClient is a mock of ShardDistributorExecutorAPIYARPCClient interface.
type MockShardDistributorExecutorAPIYARPCClient struct {
	ctrl     *gomock.Controller
	recorder *MockShardDistributorExecutorAPIYARPCClientMockRecorder
	isgomock struct{}
}

// MockShardDistributorExecutorAPIYARPCClientMockRecorder is the mock recorder for MockShardDistributorExecutorAPIYARPCClient.
type MockShardDistributorExecutorAPIYARPCClientMockRecorder struct {
	mock *MockShardDistributorExecutorAPIYARPCClient
}

// NewMockShardDistributorExecutorAPIYARPCClient creates a new mock instance.
func NewMockShardDistributorExecutorAPIYARPCClient(ctrl *gomock.Controller) *MockShardDistributorExecutorAPIYARPCClient {
	mock := &MockShardDistributorExecutorAPIYARPCClient{ctrl: ctrl}
	mock.recorder = &MockShardDistributorExecutorAPIYARPCClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShardDistributorExecutorAPIYARPCClient) EXPECT() *MockShardDistributorExecutorAPIYARPCClientMockRecorder {
	return m.recorder
}

// Heartbeat mocks base method.
func (m *MockShardDistributorExecutorAPIYARPCClient) Heartbeat(arg0 context.Context, arg1 *sharddistributorv1.HeartbeatRequest, arg2 ...yarpc.CallOption) (*sharddistributorv1.HeartbeatResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Heartbeat", varargs...)
	ret0, _ := ret[0].(*sharddistributorv1.HeartbeatResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Heartbeat indicates an expected call of Heartbeat.
func (mr *MockShardDistributorExecutorAPIYARPCClientMockRecorder) Heartbeat(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Heartbeat", reflect.TypeOf((*MockShardDistributorExecutorAPIYARPCClient)(nil).Heartbeat), varargs...)
}
